#pragma once

#define TYPE_ERROR 1
#define TYPE_SERVER_LOG 2
#define TYPE_SUBSCRIBE_TO_LOGS 3
#define TYPE_SEND_COMMAND 4
#define TYPE_DISABLE_SERVER 5
#define TYPE_ENABLE_SERVER 6
#define TYPE_RESTART_SERVER 7
