worker_processes 1;
daemon off;

error_log /dev/stdout warn;
pid /dev/null; 

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    lua_package_path "lua/?.lua;;";

    server {
        listen 8081;

        location /ws {
            content_by_lua_file lua/websocket.lua;
        }
    }
}
